### ISSUE TITLE
Grafana dasboard amélioration

### ISSUE THREAD

**Issue by roumano** [m4dm4rtig4n/node-red-enedis-gateway#1]
Au sujet du Grafana  

d'abord merci, super boulot ! voici quelques améliorations : 

- Petit erreur sur le « Electricity Consumption - per Day (k)Wh »
Comme les données sont par tranches de 30minutes (et non par heure) , il faut rajouter un math( /2 )
- Consommation mensuelle
  - Alias : Je recommande l'alias en **Consommation {année: $tag_year , mois: $tag_month}**
année avant mois, sinon le trie est merdique
  - Overrides : 
    - fileds with name :n'est pas utilisable car on a 1 field par mois
    - Field with name matching regex : perso, j'arrive pas a utiliser dans ce cas là

    - j'ai contourner le souci en mettent : Field with type : Numeric, du coup, le cell display mode (a LCD gauge ) et l'unit est fonctionel ... (et on peut aussi rajouter une decimals )
- Power Consumption Values per day
J'ai crée un nouveau tableau avec la conso par jour : 
SELECT sum("value")  / 2 FROM "consumption_load_curve" WHERE $timeFilter GROUP BY time(1d,-1h) fill(null)
le ",1h" est important sinon le calcl est faux a cause des soucis avec UTC , ...
  - Override:
Fileds with name : Time
Unit : "time: YYYY-MM-DD"
Du coup la date est dans un format "jolie"

**Comment by m4dm4rtig4n** [comment]
Hello @roumano, merci pour tes retours déjà et oui il y a effectivement pas mal de bug sur la dashboard :p
J'ai commencé à en fix plusieurs, mais j'ai du mal à avancer par manque de temps...

Après si tu les as fix, n'hésite pas à faire une PR avec tes évolutions :p

**Comment by roumano** [comment]
Je vais essayer (essayer, car la dernière fois que j'ai tenté de faire ça j'ai vraiment galérer pour faire une PR qu'avec les changement
Car avec le process grafana (surtout si on a pas la meme version de grafana)   ( import, modification, export ) m'avait changer toute la structure du fichier, il faut donc après comparer les changements, intégrer qu'une partie, vérifier , ...

**Comment by roumano** [comment]
Je vient de faire un PR ( https://github.com/m4dm4rtig4n/node-red-enedis-gateway/pull/2 ) , comme je penser, c'est bien la merde pour faire un PR qu'avec ce qui change (surtout que j'ai pas la meme version de grafana ... )

**Comment by cvalentin-adeo** [comment]
Pour l'histoire des PT10/30/60M, je pense que je vais rework un truc au niveau de Node-RED car c'est la merde à gérer sur Grafana et mettre directement la bonne data dans l'influxdb.

**Comment by m4dm4rtig4n** [comment]
Pour l'histoire des PT10/30/60M, je pense que je vais rework un truc au niveau de Node-RED car c'est la merde à gérer sur Grafana et mettre directement la bonne data dans l'influxdb.

**Comment by m4dm4rtig4n** [comment]
Hello @roumano ,

Pour information je viens de faire un push qui à rework 2 3 truc :) 

NodeRED :

- Je ne stocke plus la donnée en PT10/30/60M, mais directement à la bonne valeurs dans l'influxdb.
- Ajout d'un mode retry (3 fois), lors d'un soucis au niveau du retour des APIs configurable dans le node "Set URL + Global conf"
- Ajout d'une queue au lieu d'un rate limite sur les demandes aux APIs (permet d'alléger le nombre de demandent aux API sans pour autant ralentir le processus d'intégration)

Grafana :
- Prise en compte du changement des PT10/30/60M
- Ajout de graph pour la consomation historique (2021/2020/2019)
