### ISSUE TITLE
Ajout d'une documentation pour installer le Flow 

### ISSUE THREAD

**Issue by welcoMattic** [m4dm4rtig4n/node-red-enedis-gateway#5]
Merci pour ce repo,

Il manque une documentation pour installer le Flow dans NodeRED (je vois 2 fichiers .flow, comment les utiliser ?).
Un explication du fonctionnement serait également la bienvenue, les commits n'étant pas très explicite sur les modifications apportées au cours du temps.

Merci encore, :pray:

**Comment by m4dm4rtig4n** [comment]
C'est fait ;)
