### ISSUE TITLE
Erreur à l'import du flow

### ISSUE THREAD

**Issue by DarkAdibou** [m4dm4rtig4n/node-red-enedis-gateway#6]
Bonjour

Impossible d'importer le flow. Node-red m'indique 2 erreurs:

05/02/2021 à 01:32:24node: get list Flows
msg : string[16]
"JSON parse error"
05/02/2021 à 01:32:24node: search ID of Flows
function : (error)
"TypeError: msg.payload.forEach is not a function"

des idées ?

Merci !

**Comment by cvalentin-adeo** [comment]
Hello @DarkAdibou , ceci ce produit quand tu lance l'inject d'import ?

**Comment by DarkAdibou** [comment]
Oui exactement. J'ai pourtant bien importé le flow d'import, ainsi que les nodes complémentaires dans la palette.

**Comment by cvalentin-adeo** [comment]
Tu est sur quelle version de NodeRED ?

**Comment by mvaullerin** [comment]
Bonjour,

J'ai le même problème, je suis sur NodeRED 8.1.2

**Comment by m4dm4rtig4n** [comment]
NodeRED 8.1.2 ?

Ta prit une faille spacio-temporel, la dernière est la 1.2.9 :rofl: 

Je présume que vous avez bien suivie la procédure d'installation, si vous avez déjà importer la subfunction il est possible que ça génère ce bug.

Pour repartir en mode clean : 
- Suppresion de l'onglet Enedis
- Suppresion de la subfunction "Github to flow"
- Refaire la procédure d'installation.

**Comment by jiquem** [comment]
Cela ne fonctionne toujours pas

**Comment by m4dm4rtig4n** [comment]
La fusion à froid ? ouai je sais...
Sans plus d'explication, je ne vais pas pouvoir t'aider :/

**Comment by jiquem** [comment]
Effectivement, on peut faire plus clair. ;)
Je n'arrive pas à importer le flow.
J'avais un flow qui fonctionnait, mais qui c'est brusquement arrêté de fonctionner il y a 10 jours.
J'ai donc, voulu importer le nouveau flow, mais sans succès.
Suite à cela, j'ai tout supprimer, (flow, rednode..) et reparti de 0, mais je rencontre le problème suivant lorsque je clique sur "Import"

![Capture d’écran 2021-06-26 à 10 32 43](https://user-images.githubusercontent.com/1716813/123507477-ee214500-d669-11eb-81b0-77340129865a.png)

**Comment by VonOx** [comment]
Idem sur une fresh install V2.0.6
