### ISSUE TITLE
Erreur à l'import du flow

### ISSUE THREAD

**Issue by DuchkPy** [m4dm4rtig4n/node-red-enedis-gateway#7]
Bonjour

Lors du lancement de l'inject du 1er flow (importé via le fichier .json), il me sort l'erreur :
```
Unexpected token < in JSON at position 0
```

J'ai testé sur une instance de Node-Red fraiche sur debian, et dans HA, dans les 2 cas, j'ai la même erreur.

**Comment by bdbogjoe** [comment]
j'ai exactement le même pb, une solution ?

**Comment by bdbogjoe** [comment]
![image](https://user-images.githubusercontent.com/1301462/118411986-c36dc500-b697-11eb-88ff-314e9e648d5c.png)

**Comment by m4dm4rtig4n** [comment]
Avez-vous essayer d'ouvrir le node Credential et de le refermer ?

**Comment by bdbogjoe** [comment]
J’ai finalement réussi en modifiant le node

**Comment by DuchkPy** [comment]
> 
> 
> J’ai finalement réussi en modifiant le node

Peux-tu m'en dire plus sur le noeud modifié ?

**Comment by jiquem** [comment]
> Avez-vous essayer d'ouvrir le node Credential et de le refermer ?

oui, j'ai essayé

**Comment by m4dm4rtig4n** [comment]
Quand je vois le message d'erreur, il faut ouvrir et fermer le node Credential.

**Comment by DuchkPy** [comment]
@m4dm4rtig4n, le message affiché par @bdbogjoe contient 2 alertes concernant les credentials, et 1 erreur.
Pour ma part je n'ai pas les 2 alertes concernant les credentials, uniquement l'erreur `Unexpected token < in JSON at position 0`

**Comment by cvalentin-dkt** [comment]
> @m4dm4rtig4n, le message affiché par @bdbogjoe contient 2 alertes concernant les credentials, et 1 erreur.
> Pour ma part je n'ai pas les 2 alertes concernant les credentials, uniquement l'erreur `Unexpected token < in JSON at position 0`

A tu essayer de repartir de 0 en suivant bien la procédure d'installation ?
